# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-16 07:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0005_auto_20170905_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='title',
            field=models.TextField(default='To-Do List'),
        ),
    ]
