# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-16 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0006_list_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
